Repository prgrms-fe-devcourse/FEDC4_SCRAWL_Yohan, pull requests merged in 2023-09, with the labels that each got.

#11 [ 이진욱 ] Axios 인스턴스 구현
  src/@types/index.d.ts
  src/apis/axiosInstance.ts
  src/apis/channel/getChannels.ts
  src/apis/interceptors.ts
  src/constants/api.ts
  src/hooks/api/useChannelsQuery.ts
  src/main.tsx
  src/types/Channel.ts
Labels: 분류 : 기능 추가 / 개선, 우선순위 : 긴급

#14 [김동현] css 속성 오타 수정
  src/components/atoms/Button.tsx
  src/components/atoms/Input.tsx
Labels: 분류 : 버그, 우선순위 : 긴급

#12 [ 안혜수 ] atom 제작 - 텍스트
  .prettierrc
  package-lock.json
  package.json
  src/App.tsx
  src/assets/svg/index.ts
  src/assets/svg/logo.svg
  src/components/atoms/Icon.tsx
  src/components/atoms/Text.tsx
  src/stories/components/atoms/Icon.stories.tsx
  src/stories/components/atoms/Text.stories.tsx
  tsconfig.json
  vite.config.ts
Labels: 분류 : 기능 추가 / 개선, 우선순위 : 긴급

#24 [ 혜수 ] global css setting font & reset 설정
  src/main.tsx
  src/styles/globalStyles.ts
Labels: 분류 : 기능 추가 / 개선, 우선순위 : 낮음

#26 [ 진욱 ] Molecules 구현
  src/components/atoms/Flex.tsx
  src/components/molecules/Tag.tsx
  src/components/molecules/UserInfo.tsx
  src/stories/components/molecules/Tag.stories.tsx
  src/stories/components/molecules/UserInfo.stories.tsx
Labels: 분류 : 기능 추가 / 개선, 우선순위 : 긴급

#25 [ 김동현 ] API URL 상수화, (API 모델, API 파라미터) 타입정의
  src/apis/channel/getChannels.ts
  src/constants/api.ts
  src/types/apis/articles/CreateArticle.ts
  src/types/apis/articles/DeleteArticle.ts
  src/types/apis/articles/GetArticle.ts
  src/types/apis/articles/GetArticles.ts
  src/types/apis/articles/UpdateArticle.ts
  src/types/apis/channels/CreateChannel.ts
  src/types/apis/channels/GetChannel.ts
  src/types/apis/channels/GetChannels.ts
  src/types/apis/comments/CreateComment.ts
  src/types/apis/comments/DeleteComment.ts
  src/types/apis/etc/SearchAll.ts
  src/types/apis/likes/CreateLike.ts
  src/types/apis/likes/DeleteLike.ts
  src/types/apis/notifications/CreateNotification.ts
  src/types/apis/notifications/GetNotifications.ts
  src/types/apis/users/GetUser.ts
  src/types/apis/users/GetUsers.ts
  src/types/apis/users/Login.ts
  src/types/apis/users/SearchUsers.ts
  src/types/apis/users/Signup.ts
  src/types/apis/users/UpdatePassword.ts
  src/types/apis/users/UpdateUser.ts
  src/types/apis/users/UploadProfile.ts
  src/types/models/Article.ts
  src/types/models/Channel.ts
  src/types/models/Comment.ts
  src/types/models/Like.ts
  src/types/models/Message.ts
  src/types/models/Notifications.ts
  src/types/models/User.ts
Labels: 분류 : 기능 추가 / 개선, 우선순위 : 중간

#28 [ 김동현 ] Button, Input onClick, onChange처리, 기본값 props 타입 옵셔널 정의
  src/components/atoms/Button.tsx
  src/components/atoms/Input.tsx
  src/stories/components/atoms/Button.stories.tsx
  src/stories/components/atoms/Input.stories.tsx
Labels: 분류 : 버그, 우선순위 : 긴급

#33 [ 혜수 ] 아이콘 + 텍스트, FloatingButton molecule 제작 & svg 파일 추가
  src/assets/svg/alert.svg
  src/assets/svg/folder.svg
  src/assets/svg/home.svg
  src/assets/svg/index.ts
  src/assets/svg/like.svg
  src/assets/svg/message.svg
  src/assets/svg/my.svg
  src/assets/svg/question.svg
  src/assets/svg/search.svg
  src/assets/svg/upperBracket.svg
  src/components/atoms/Icon.tsx
  src/components/atoms/Text.tsx
  src/components/molecules/FloatingButton.tsx
  src/components/molecules/IconText.tsx
  src/stories/components/molecules/FloatingButton.stories.tsx
  src/stories/components/molecules/IconText.stories.tsx
Labels: 분류 : 기능 추가 / 개선, 우선순위 : 긴급

#41 [ 진욱 ] Article 타입 수정
  src/types/apis/articles/CreateArticle.ts
  src/types/apis/articles/UpdateArticle.ts
  src/types/models/Article.ts
Labels: 분류 : 기능 추가 / 개선, 우선순위 : 긴급

#43 fix: onClick, onChange 타입 속성 삭제
  src/components/atoms/Button.tsx
  src/components/atoms/Input.tsx
  src/stories/components/atoms/Button.stories.tsx
Labels: 분류 : 배포, 우선순위 : 긴급

#45 [ 혜수 ] Hotfix - FloatingButton 충돌 수정
  src/assets/svg/bracketLower.svg
  src/assets/svg/bracketUpper.svg
  src/assets/svg/index.ts
  src/components/molecules/FloatingButton.tsx
  src/stories/components/molecules/FloatingButton.stories.tsx
Labels: 분류 : 기능 추가 / 개선, 우선순위 : 긴급

#46 [ 진욱 ] PageTemplate 제작
  src/App.tsx
  src/components/templates/PageTemplate/PageTemplate.styles.ts
  src/components/templates/PageTemplate/PageTemplate.tsx
  src/components/templates/PageTemplate/index.ts
  src/main.tsx
  src/router/index.tsx
  src/styles/globalStyles.ts
Labels: 분류 : 기능 추가 / 개선, 우선순위 : 긴급

#47 [ 진욱 ] ChannelPage 구현, Card organism 구현
  src/apis/article/createArticle.ts
  src/apis/article/getArticlesByChannelId.ts
  src/components/molecules/IconText.tsx
  src/components/molecules/Tag.tsx
  src/components/organisms/Card/Card.styles.ts
  src/components/organisms/Card/Card.tsx
  src/components/organisms/Card/CardFooter.styles.ts
  src/components/organisms/Card/CardFooter.tsx
  src/components/organisms/Card/CardSkeleton.tsx
  src/components/organisms/Card/Tags.styles.ts
  src/components/organisms/Card/Tags.tsx
  src/components/organisms/Card/index.ts
  src/components/templates/PageTemplate/PageTemplate.styles.ts
  src/components/templates/PageTemplate/PageTemplate.tsx
  src/constants/card.ts
  src/hooks/api/useArticlesByChannelIdQuery.ts
  src/hooks/api/useChannelsQuery.ts
  src/pages/ChannelPage/ChannelPage.styles.ts
  src/pages/ChannelPage/ChannelPage.tsx
  src/pages/ChannelPage/ChannelPageSkeleton.tsx
  src/pages/ChannelPage/index.ts
  src/router/index.tsx
  src/stories/components/organisms/Card.stories.tsx
  src/styles/lineClamp.ts
  src/types/apis/articles/CreateArticle.ts
  src/types/apis/articles/UpdateArticle.ts
  src/types/models/Article.ts
  src/types/models/User.ts
  src/utils/ErrorBoundary.ts
Labels: 분류 : 기능 추가 / 개선, 우선순위 : 긴급

#48 [ 김동현 ] 유저 폼 Molecule 만들기, (로그인, 회원가입) 페이지 만들기
  src/apis/interceptors.ts
  src/apis/user/login.ts
  src/apis/user/signUp.ts
  src/components/molecules/UserForm.tsx
  src/constants/api.ts
  src/pages/LoginPage.tsx
  src/pages/SignUpPage.tsx
  src/router/index.tsx
  src/stores/token.store.ts
  src/stories/components/molecules/UserForm.stories.tsx
Labels: 분류 : 기능 추가 / 개선, 우선순위 : 긴급

#54 [ 혜수 ] svg 사용할 때 콘솔에서 에러메시지 출력되는 문제 해결
  src/assets/svg/alert.svg
  src/assets/svg/bracketLower.svg
  src/assets/svg/bracketUpper.svg
  src/assets/svg/folder.svg
  src/assets/svg/home.svg
  src/assets/svg/like.svg
  src/assets/svg/logo.svg
  src/assets/svg/message.svg
  src/assets/svg/my.svg
  src/assets/svg/question.svg
  src/assets/svg/search.svg
Labels: 우선순위 : 낮음, 분류 : 버그

#58 [ 진욱 ] svg 색깔 안바뀌는 것 수정
  src/assets/svg/alert.svg
  src/assets/svg/bracketLower.svg
  src/assets/svg/bracketUpper.svg
  src/assets/svg/folder.svg
  src/assets/svg/home.svg
  src/assets/svg/like.svg
  src/assets/svg/message.svg
  src/assets/svg/my.svg
  src/assets/svg/placeholderUser.svg
  src/assets/svg/question.svg
  src/assets/svg/search.svg
  src/components/organisms/Card/Card.tsx
  src/stories/components/atoms/Icon.stories.tsx
Labels: 분류 : 버그, 우선순위 : 긴급

#52 [ 혜수 ] Article 생성 Organism 제작
  package-lock.json
  package.json
  src/components/organisms/ArticleWrite/ArticleEditor.tsx
  src/components/organisms/ArticleWrite/ArticleTag.tsx
  src/components/organisms/ArticleWrite/ArticleTitle.tsx
  src/components/organisms/ArticleWrite/ChannelSelect.tsx
  src/components/organisms/ArticleWrite/index.tsx
  src/hooks/useDetectClose.ts
  src/router/index.tsx
Labels: 분류 : 기능 추가 / 개선, 우선순위 : 긴급

#50 [ 진욱 ] useLoggedIn 훅 구현, themeStore persist 적용
  src/apis/user/getUserByToken.ts
  src/components/organisms/Card/CardFooter.styles.ts
  src/constants/theme.ts
  src/hooks/api/useUserByTokenQuery.ts
  src/hooks/useLoggedIn.ts
  src/pages/ChannelPage/ChannelPage.tsx
  src/pages/ChannelPage/ChannelPageSkeleton.tsx
  src/pages/HomePage.tsx
  src/router/index.tsx
  src/stores/theme.store.ts
  src/stores/token.store.ts
  src/utils/isDarkMode.ts
Labels: 분류 : 기능 추가 / 개선, 우선순위 : 긴급

#55 [ 김동현 ] 댓글 폼 molecule 만들기
  src/apis/comment/createComment.ts
  src/apis/user/authUser.ts
  src/components/molecules/CommentForm.tsx
  src/stories/components/molecules/CommentForm.stories.tsx
  src/types/apis/users/AuthUser.ts
Labels: 분류 : 기능 추가 / 개선, 우선순위 : 중간

#64 [ 혜수 ] 사이드바 Organism 제작
  src/assets/svg/index.ts
  src/assets/svg/moon.svg
  src/assets/svg/sun.svg
  src/components/organisms/Sidebar/ThemeToggle.tsx
  src/components/organisms/Sidebar/index.tsx
  src/components/templates/PageTemplate/PageTemplate.tsx
Labels: 분류 : 기능 추가 / 개선, 우선순위 : 긴급

#61 [ 진욱 ] myInfoStore 구현 및 Login 컴포넌트 구현
  src/App.tsx
  src/components/Login.tsx
  src/stores/myInfo.store.ts
Labels: 분류 : 기능 추가 / 개선, 우선순위 : 중간

#63 [ 진욱 ] Article organism 구현
  package-lock.json
  package.json
  src/App.tsx
  src/apis/article/deleteArticle.ts
  src/apis/article/getArticle.ts
  src/apis/like/createLike.ts
  src/apis/like/deleteLike.ts
  src/components/organisms/Article/Article.styles.ts
  src/components/organisms/Article/Article.tsx
  src/components/organisms/Article/ArticleSkeleton.tsx
  src/components/organisms/Article/index.ts
  src/components/organisms/Card/CardFooter.tsx
  src/components/organisms/Tags/Tags.styles.ts
  src/components/organisms/Tags/Tags.tsx
  src/components/organisms/Tags/index.ts
  src/components/templates/PageTemplate/PageTemplate.styles.ts
  src/hooks/api/useArticleCreateMutation.ts
  src/hooks/api/useArticleDeleteMutation.ts
  src/hooks/api/useArticleQuery.ts
  src/hooks/api/useLikeCreateMutation.ts
  src/hooks/api/useLikeDeleteMutation.ts
  src/router/index.tsx
  src/styles/globalStyles.ts
  src/utils/htmlToPlainText.ts
Labels: 분류 : 기능 추가 / 개선, 우선순위 : 긴급

#67 [ 혜수 ] 사이드바 로그아웃 버튼 디자인 변경
  src/components/organisms/Sidebar/ThemeToggle.tsx
  src/components/organisms/Sidebar/index.tsx
Labels: 분류 : 기능 추가 / 개선, 우선순위 : 낮음

#71 [ 혜수 ] 다크모드 토글버튼 패딩 제거
  src/components/organisms/Sidebar/ThemeToggle.tsx
Labels: 분류 : 기능 추가 / 개선, 우선순위 : 낮음

#66 [ 김동현 ] 댓글 박스, 질문/답변 말풍선 컴포넌트, 질문 조회 페이지 제작
  package-lock.json
  package.json
  src/apis/article/getArticleByArticleId.ts
  src/components/molecules/CommentForm.tsx
  src/components/organisms/CommentBox.tsx
  src/hooks/api/useArticleByArticleIdQuery.ts
  src/pages/QuestionPage.tsx
  src/router/index.tsx
  src/stories/components/organisms/CommentBox.stories.tsx
  src/types/models/Article.ts
Labels: 분류 : 기능 추가 / 개선, 우선순위 : 중간

#74 [ 진욱 ] 게시글 좋아요, 삭제 api 붙이기
  src/App.tsx
  src/apis/article/deleteArticle.ts
  src/apis/like/deleteLike.ts
  src/components/Login.tsx
  src/components/organisms/Article/Article.styles.ts
  src/components/organisms/Article/Article.tsx
  src/components/organisms/Sidebar/index.tsx
  src/constants/api.ts
  src/hooks/api/useArticleCreateMutation.ts
  src/hooks/api/useArticleDeleteMutation.ts
  src/hooks/api/useArticlesByChannelIdQuery.ts
  src/hooks/api/useLikeCreateMutation.ts
  src/hooks/api/useLikeDeleteMutation.ts
  src/hooks/api/useUserByTokenQuery.ts
  src/main.tsx
  src/pages/LoginPage.tsx
  src/stores/myInfo.store.ts
  src/styles/globalStyles.ts
  src/types/apis/articles/DeleteArticle.ts
  src/utils/AuthError.ts
  src/utils/AuthErrorBoundary.ts
Labels: 분류 : 기능 추가 / 개선, 우선순위 : 긴급

#76 [ 진욱, 동현 ] 아티클, 질문 페이지 통합 및 댓글 관련 기능 추가
  src/apis/article/getArticle.ts
  src/apis/article/getArticleByArticleId.ts
  src/apis/article/getArticlesByChannelId.ts
  src/apis/comment/deleteComment.ts
  src/components/atoms/Gap.tsx
  src/components/molecules/CommentForm.tsx
  src/components/organisms/Article/Article.styles.ts
  src/components/organisms/Article/Article.tsx
  src/components/organisms/ArticleHeader/ArticleHeader.styles.ts
  src/components/organisms/ArticleHeader/ArticleHeader.tsx
  src/components/organisms/ArticleHeader/index.ts
  src/components/organisms/CommentBox.tsx
  src/components/organisms/Thread/Thread.styles.ts
  src/components/organisms/Thread/Thread.tsx
  src/components/organisms/Thread/index.ts
  src/constants/api.ts
  src/constants/index.ts
  src/hooks/api/useArticleByArticleIdQuery.ts
  src/hooks/api/useCommentCreateMutation.ts
  src/hooks/api/useCommentDeleteMutation.ts
  src/pages/QuestionPage.tsx
  src/router/index.tsx
  src/stories/components/organisms/CommentBox.stories.tsx
  src/stories/components/organisms/Thread.stories.tsx
  src/types/apis/comments/CreateComment.ts
  src/types/apis/comments/DeleteComment.ts
  src/types/models/Article.ts
Labels: 분류 : 기능 추가 / 개선, 우선순위 : 중간

#80 [ 혜수 ] 글 작성 페이지 API 연결 완료
  src/components/organisms/ArticleWrite/ArticleTag.tsx
  src/components/organisms/ArticleWrite/ChannelSelect.tsx
  src/components/organisms/ArticleWrite/index.tsx
Labels: 분류 : 기능 추가 / 개선, 우선순위 : 긴급

#82 [ 진욱 ] Modal 컴포넌트 구현
  src/components/atoms/Modal.tsx
  src/hooks/useClickAway.ts
  src/stories/components/atoms/Modal.stories.tsx
Labels: 분류 : 기능 추가 / 개선, 우선순위 : 낮음

#85 [ 진욱 ] 카드 컴포넌트 텍스트 overflow 되는 문제 수정
  src/components/organisms/Card/CardFooter.styles.ts
  src/components/organisms/Card/CardFooter.tsx
Labels: 분류 : 버그, 우선순위 : 긴급

#88 [ 진욱 ] 좋아요 관련 버그 수정
  src/components/organisms/ArticleHeader/ArticleHeader.tsx
Labels: 분류 : 버그, 우선순위 : 긴급

#89 [ 진욱 ] 알림 드롭다운 구현
  src/apis/notification/createNotification.ts
  src/apis/notification/getNotifications.ts
  src/apis/notification/readNotifications.ts
  src/components/atoms/Dropdown.tsx
  src/components/organisms/ArticleHeader/ArticleHeader.tsx
  src/components/organisms/NotiDropdown/NotiDropdown.styles.ts
  src/components/organisms/NotiDropdown/NotiDropdown.tsx
  src/components/organisms/NotiDropdown/index.ts
  src/hooks/api/useNotificationCreateMutation.ts
  src/hooks/api/useNotificationsQuery.ts
  src/hooks/api/useNotificationsReadMutation.ts
  src/types/apis/notifications/CreateNotification.ts
  src/types/apis/notifications/GetNotifications.ts
  src/types/models/Notification.ts
  src/types/models/User.ts
Labels: 분류 : 기능 추가 / 개선, 우선순위 : 낮음

#83 [ 진욱 ] react hot toast 의존성 추가
  package-lock.json
  package.json
  src/App.tsx
  src/components/Toaster.tsx
Labels: 분류 : 기능 추가 / 개선, 우선순위 : 낮음

#90 [ 동현 ] 유저 정보 페이지 작성
  src/apis/article/getArticleByUserId.ts
  src/apis/user/getUser.ts
  src/apis/user/updateUser.ts
  src/apis/user/uploadProfile.ts
  src/assets/svg/done.svg
  src/assets/svg/edit.svg
  src/assets/svg/index.ts
  src/hooks/api/useArticleByUserIdQuery.ts
  src/hooks/api/useUserProfileUploadMutation.ts
  src/hooks/api/useUserQuery.ts
  src/hooks/api/useUserUpdateMutation.ts
  src/pages/UserPage/ArticleList.tsx
  src/pages/UserPage/ChannelTab.tsx
  src/pages/UserPage/UserInfo.tsx
  src/pages/UserPage/UserPage.style.ts
  src/pages/UserPage/UserPage.tsx
  src/router/index.tsx
Labels: 분류 : 기능 추가 / 개선, 우선순위 : 중간

#96 [ 혜수 ] 사이드바 채널 생성시 채널 동적으로 변경 되도록 수정, 디자인 수정
  src/components/atoms/Icon.tsx
  src/components/molecules/IconText.tsx
  src/components/organisms/Sidebar/Sidebar.styles.ts
  src/components/organisms/Sidebar/index.tsx
Labels: 분류 : 기능 추가 / 개선, 우선순위 : 중간

#93 [ 진욱 ] 채널 페이지 무한스크롤 구현
  src/hooks/api/useArticlesByChannelIdQuery.ts
  src/hooks/useIntersectionObserver.ts
  src/pages/ChannelPage/ChannelPage.tsx
Labels: 분류 : 기능 추가 / 개선, 우선순위 : 중간

#97 [ 혜수 ] 새 글 작성 버튼 & 맨 위로가기 버튼 추가
  src/assets/svg/add.svg
  src/assets/svg/expandLess.svg
  src/assets/svg/expandMore.svg
  src/assets/svg/index.ts
  src/components/molecules/FloatingButton.tsx
  src/components/organisms/ArticleWrite/ChannelSelect.tsx
  src/components/organisms/FloatingButtons/FloatingButtons.styles.ts
  src/components/organisms/FloatingButtons/FloatingButtons.tsx
  src/components/organisms/FloatingButtons/index.tsx
  src/components/templates/PageTemplate/PageTemplate.styles.ts
  src/components/templates/PageTemplate/PageTemplate.tsx
  src/stories/components/atoms/Icon.stories.tsx
Labels: 분류 : 기능 추가 / 개선, 우선순위 : 긴급

#105 [ 진욱 ] CardFooter 고정 높이로 수정
  src/components/organisms/Card/CardFooter.styles.ts
Labels: 분류 : 버그, 우선순위 : 긴급

#106 [ 혜수 ] 사이드바 로그인 여부에 따라 다르게 보이게 수정
  src/components/organisms/Sidebar/Sidebar.styles.ts
  src/components/organisms/Sidebar/index.tsx
Labels: 분류 : 기능 추가 / 개선, 우선순위 : 긴급

#107 [ 동현 ] 유저페이지 수정
  src/pages/UserPage/ArticleList.tsx
  src/pages/UserPage/UserInfo.tsx
Labels: 분류 : 버그, 우선순위 : 긴급

#108 [ 혜수 ] 글 작성시 채널과 제목 입력이 되어있지 않을 때 toast 추가
  src/components/organisms/ArticleWrite/index.tsx
Labels: 분류 : 기능 추가 / 개선, 우선순위 : 중간

#110 [ 혜수 ] 사이드바 내 정보 클릭시 자신의 정보 페이지로 이동 추가
  src/components/organisms/Sidebar/index.tsx
Labels: 분류 : 기능 추가 / 개선, 우선순위 : 긴급

#111 [ 동현 ] 비밀번호 변경 페이지
  src/apis/user/updatePassword.ts
  src/components/atoms/Button.tsx
  src/hooks/api/useUserPasswordUpdateMutation.ts
  src/pages/PasswordPage/PasswordPage.tsx
  src/router/index.tsx
Labels: 분류 : 기능 추가 / 개선, 우선순위 : 중간

#113 [ 동현 ] 댓글 폼 컴포넌트, 버튼 textContent 수정
  src/components/molecules/CommentForm.tsx
Labels: 분류 : 버그, 우선순위 : 중간

#116 [ 혜수 ] 로그인 하지 않고 '/create' 접근시 에러 throw
  src/components/organisms/ArticleWrite/index.tsx
Labels: 분류 : 기능 추가 / 개선, 우선순위 : 긴급

#122 [ 혜수 ] 맨 위로 가기 버튼 페이지 제일 위에 있을 때 보이지 않게 하기
  src/components/organisms/FloatingButtons/FloatingButtons.styles.ts
  src/components/organisms/FloatingButtons/FloatingButtons.tsx
  src/components/organisms/FloatingButtons/index.tsx
  src/components/templates/PageTemplate/PageTemplate.tsx
Labels: 분류 : 기능 추가 / 개선, 우선순위 : 낮음

#125 [ 동현 ] 댓글 폼 컴포넌트 에디터 교체, 비로그인 시 댓글 폼 숨김
  src/components/molecules/CommentForm.tsx
  src/components/organisms/Article/Article.tsx
Labels: 분류 : 기능 추가 / 개선, 우선순위 : 중간

#129 [ 동현 ] 쓰레드에서 UserInfo 클릭 시 유저 페이지 이동 기능
  src/components/organisms/Thread/Thread.styles.ts
  src/components/organisms/Thread/Thread.tsx
Labels: 분류 : 기능 추가 / 개선, 우선순위 : 중간

#128 [ 혜수 ] 채널 Select 컴포넌트 z-index 수정 및 ArticleWrite 리팩토링
  ArticleWriteEditor로
  src/components/molecules/CommentForm.tsx
  src/components/organisms/ArticleWrite/ArticleChannelSelect.tsx
  src/components/organisms/ArticleWrite/ArticleWrite.styles.ts
  src/components/organisms/ArticleWrite/ArticleWrite.tsx
  src/components/organisms/ArticleWrite/ArticleWriteButtons.tsx
  src/components/organisms/ArticleWrite/ArticleWriteEditor.tsx
  src/components/organisms/ArticleWrite/ArticleWriteTag.tsx
  src/components/organisms/ArticleWrite/ArticleWriteTitle.tsx
  src/components/organisms/ArticleWrite/ChannelSelect.tsx
  src/components/organisms/ArticleWrite/index.tsx
  src/router/index.tsx
Labels: 분류 : 기능 추가 / 개선, 우선순위 : 중간

#126 [ 혜수 ] 사이드바 채널만 overflow로 변경 & 사이드바 리팩토링
  src/components/organisms/Sidebar/Sidebar.styles.ts
  src/components/organisms/Sidebar/Sidebar.tsx
  src/components/organisms/Sidebar/SidebarChannels.tsx
  src/components/organisms/Sidebar/SidebarFooter.tsx
  src/components/organisms/Sidebar/SidebarHeader.tsx
  src/components/organisms/Sidebar/SidebarMain.tsx
  src/components/organisms/Sidebar/index.tsx
  src/components/templates/PageTemplate/PageTemplate.tsx
  src/pages/UserPage/UserPage.style.ts
Labels: 분류 : 기능 추가 / 개선, 우선순위 : 중간

#131 [ 동현 ] 본인 아닐 시 유저정보 이미지 변경 불가, 전체글 보여주기 탭
  src/pages/UserPage/ArticleList.tsx
  src/pages/UserPage/ChannelTab.tsx
  src/pages/UserPage/UserInfo.tsx
Labels: 분류 : 기능 추가 / 개선, 우선순위 : 중간

#135 [ 동현 ] 글 삭제, 댓글 삭제 시 모달 띄우기
  src/components/molecules/ConfirmModal.tsx
  src/components/organisms/ArticleHeader/ArticleHeader.tsx
  src/components/organisms/Thread/Thread.tsx
Labels: 분류 : 기능 추가 / 개선, 우선순위 : 중간

#141 [ 동현 ] 로그인, 회원가입, 패스워드 페이지 엔터키 제출 기능
  src/pages/LoginPage.tsx
  src/pages/PasswordPage.tsx
  src/pages/SignUpPage.tsx
  src/utils/withEnter.ts
Labels: 분류 : 기능 추가 / 개선, 우선순위 : 중간

#159 [ 혜수 ] 채널 한글화 작업
  src/components/organisms/Sidebar/SidebarChannels.tsx
Labels: 분류 : 기능 추가 / 개선, 우선순위 : 긴급

#137 [ 동현 ] 빈 문자열로 댓글을 추가 할 시, 에러 발생
  src/components/molecules/CommentForm.tsx
  src/hooks/api/useCommentCreateMutation.ts
Labels: 분류 : 버그, 우선순위 : 중간

#148 [ 동현 ] 회원가입시, 비밀번호 확인 만들기
  src/pages/SignUpPage.tsx
Labels: 분류 : 기능 추가 / 개선, 우선순위 : 중간

#160 [ 진욱 ] 카드 리스트 그리드로 변경 및 반응형 작업
  src/components/organisms/Card/Card.styles.ts
  src/components/organisms/Card/Card.tsx
  src/components/organisms/Card/CardSkeleton.tsx
  src/components/organisms/CardList/CardList.styles.ts
  src/components/organisms/CardList/CardList.tsx
  src/components/organisms/CardList/index.ts
  src/constants/media.ts
  src/pages/ChannelPage/ChannelPage.styles.ts
  src/pages/ChannelPage/ChannelPage.tsx
  src/pages/ChannelPage/ChannelPageSkeleton.tsx
  src/pages/UserPage/ArticleList.tsx
  src/stories/components/organisms/Card.stories.tsx
Labels: 분류 : 기능 추가 / 개선, 우선순위 : 중간

#157 [ 동현 ] 로그인, 회원가입, 비밀번호 페이지 버튼 색 통일, 로고 가운데로 위치 조정
  src/assets/svg/index.ts
  src/assets/svg/logo2.svg
  src/pages/LoginPage.tsx
  src/pages/PasswordPage.tsx
  src/pages/SignUpPage.tsx
Labels: 분류 : 기능 추가 / 개선, 우선순위 : 중간

#161 [ 진욱 ] 작성시간 보여주기 변경
  src/components/organisms/Card/CardFooter.tsx
  src/components/organisms/NotiDropdown/NotiDropdown.tsx
  src/components/organisms/Thread/Thread.tsx
  src/utils/createdAtToString.ts
Labels: 분류 : 기능 추가 / 개선, 우선순위 : 중간

#162 [ 혜수 ] 사이드바 아이콘 구글에서 새로 가져오기
  src/assets/svg/alert.svg
  src/assets/svg/alert1.svg
  src/assets/svg/home.svg
  src/assets/svg/home1.svg
  src/assets/svg/question.svg
  src/assets/svg/question1.svg
  src/assets/svg/search.svg
  src/assets/svg/search1.svg
  src/components/molecules/UserInfo.tsx
  src/components/organisms/Sidebar/Sidebar.styles.ts
  src/components/organisms/Sidebar/Sidebar.tsx
  src/components/organisms/Sidebar/SidebarMain.tsx
Labels: 분류 : 기능 추가 / 개선, 우선순위 : 낮음

#165 [ 혜수 ] 채널 아이콘 변경 & 로고 파일 변경
  src/assets/svg/AI.svg
  src/assets/svg/alert1.svg
  src/assets/svg/alertMore.svg
  src/assets/svg/back.svg
  src/assets/svg/bigData.svg
  src/assets/svg/data.svg
  src/assets/svg/devOps.svg
  src/assets/svg/embedded.svg
  src/assets/svg/folder.svg
  src/assets/svg/free.svg
  src/assets/svg/front.svg
  src/assets/svg/game.svg
  src/assets/svg/home1.svg
  src/assets/svg/index.ts
  src/assets/svg/job.svg
  src/assets/svg/logo.svg
  src/assets/svg/logo2.svg
  src/assets/svg/question.svg
  src/assets/svg/question1.svg
  src/assets/svg/search1.svg
  src/assets/svg/security.svg
  src/components/organisms/Sidebar/SidebarChannels.tsx
  src/pages/LoginPage.tsx
  src/pages/PasswordPage.tsx
  src/pages/SignUpPage.tsx
  src/stories/components/atoms/Icon.stories.tsx
Labels: 분류 : 기능 추가 / 개선, 우선순위 : 긴급

#164 [ 진욱 ] 댓글 시 알림 생성, 알림 중복 제거
  src/components/molecules/CommentForm.tsx
  src/components/organisms/Article/Article.tsx
  src/components/organisms/NotiDropdown/NotiDropdown.styles.ts
  src/components/organisms/NotiDropdown/NotiDropdown.tsx
  src/components/organisms/NotiDropdown/filterNotifications.ts
  src/stories/components/molecules/CommentForm.stories.tsx
Labels: 분류 : 기능 추가 / 개선, 우선순위 : 중간

#166 [ 진욱 ] 검색 모달 구현
  src/apis/search/searchAll.ts
  src/apis/search/searchArticles.ts
  src/apis/search/searchUsers.ts
  src/assets/svg/arrowBack.svg
  src/assets/svg/index.ts
  src/components/atoms/Conditional.tsx
  src/components/organisms/SearchModal/ArticleSearchResults.tsx
  src/components/organisms/SearchModal/SearchItem.tsx
  src/components/organisms/SearchModal/SearchModal.tsx
  src/components/organisms/SearchModal/TagSearchResults.tsx
  src/components/organisms/SearchModal/UserSearchResults.tsx
  src/components/organisms/SearchModal/index.ts
  src/components/organisms/Sidebar/SidebarMain.tsx
  src/constants/api.ts
  src/hooks/api/useSearchAllQuery.ts
  src/hooks/api/useSearchArticlesQuery.ts
  src/hooks/api/useSearchUsersQuery.ts
  src/hooks/useDebouncedEffect.ts
  src/pages/SearchPage/SearchPage.styles.ts
  src/pages/SearchPage/SearchPage.tsx
  src/router/index.tsx
  src/types/apis/etc/SearchAll.ts
Labels: 분류 : 기능 추가 / 개선, 우선순위 : 중간

#180 [ 동현 ] 채널 별 글 가져오는 슬라이더 컴포넌트 , 홈페이지 제작
  src/apis/article/getArticles.ts
  src/assets/svg/index.ts
  src/assets/svg/next.svg
  src/assets/svg/prev.svg
  src/components/organisms/ArticlesByChannelSlider/ArticlesByChannelSlider.style.ts
  src/components/organisms/ArticlesByChannelSlider/ArticlesByChannelSlider.tsx
  src/components/organisms/ArticlesByChannelSlider/CardSlider.tsx
  src/components/organisms/ArticlesByChannelSlider/index.ts
  src/hooks/api/useArticlesQuery.ts
  src/pages/HomePage.tsx
  src/router/index.tsx
Labels: 분류 : 기능 추가 / 개선, 우선순위 : 긴급

#169 [ 진욱 ] 트랜지션 - 카드, 알림, 모달
  src/components/atoms/Dropdown.tsx
  src/components/atoms/Modal.tsx
  src/components/organisms/Card/Card.styles.ts
  src/styles/globalStyles.ts
Labels: 분류 : 기능 추가 / 개선, 우선순위 : 낮음

#177 [ 진욱 ] 게시글 썸네일 없을 때 기본이미지 보여주기
  src/assets/svg/index.ts
  src/assets/svg/noImage.svg
  src/components/organisms/Card/Card.tsx
Labels: 분류 : 기능 추가 / 개선, 우선순위 : 중간

#171 [ 진욱 ] 알림 없을 때 알림 없음 표시
  src/components/organisms/NotiDropdown/NotiDropdown.styles.ts
  src/components/organisms/NotiDropdown/NotiDropdown.tsx
Labels: 분류 : 기능 추가 / 개선, 우선순위 : 중간

#179 [ 진욱 ] 검색 모달 Suspense 작업
  src/assets/svg/index.ts
  src/assets/svg/spinner.svg
  src/components/molecules/Spinning.tsx
  src/components/organisms/SearchModal/SearchModal.tsx
Labels: 분류 : 기능 추가 / 개선, 우선순위 : 중간

#174 [ 진욱 ] 검색 모달에 현재 선택된 검색옵션 알려주기
  src/components/organisms/SearchModal/SearchModal.styles.ts
  src/components/organisms/SearchModal/SearchModal.tsx
Labels: 분류 : 기능 추가 / 개선, 우선순위 : 중간

#168 [ 진욱 ] 스크롤바 스타일링, 유저페이지 스타일 변경, 채널명 한글화
  src/apis/channel/getChannels.ts
  src/components/organisms/CardList/CardList.styles.ts
  src/components/organisms/Sidebar/SidebarChannels.tsx
  src/constants/channel.ts
  src/hooks/api/useArticleDeleteMutation.ts
  src/pages/ChannelPage/ChannelPage.tsx
  src/pages/SearchPage/SearchPage.tsx
  src/pages/UserPage/ArticleList.tsx
  src/pages/UserPage/ChannelTab.tsx
  src/pages/UserPage/UserInfo.tsx
  src/pages/UserPage/UserPage.style.ts
  src/pages/UserPage/UserPage.tsx
  src/styles/globalStyles.ts
Labels: 분류 : 기능 추가 / 개선, 우선순위 : 중간

#172 [ 진욱 ] 검색 결과, 게시글 없음 표시하는 기능 추가
  src/assets/svg/index.ts
  src/assets/svg/logoAlert.svg
  src/components/molecules/EmptyAlert/EmptyAlert.styles.ts
  src/components/molecules/EmptyAlert/EmptyAlert.tsx
  src/components/molecules/EmptyAlert/index.ts
  src/components/organisms/SearchModal/ArticleSearchResults.tsx
  src/components/organisms/SearchModal/TagSearchResults.tsx
  src/components/organisms/SearchModal/UserSearchResults.tsx
  src/pages/ChannelPage/ChannelPage.tsx
Labels: 분류 : 기능 추가 / 개선, 우선순위 : 중간

#167 [ 혜수 ] 사이드바 반응형 추가 & 클릭시 배경 유지하기
  src/assets/svg/index.ts
  src/assets/svg/keyboardTab.svg
  src/assets/svg/keyboardTabRtl.svg
  src/components/molecules/FloatingButton.tsx
  src/components/organisms/Sidebar/Sidebar.styles.ts
  src/components/organisms/Sidebar/Sidebar.tsx
  src/components/organisms/Sidebar/SidebarAppearButton.tsx
  src/components/organisms/Sidebar/SidebarChannels.tsx
  src/components/organisms/Sidebar/SidebarHeader.tsx
  src/components/organisms/Sidebar/SidebarMain.tsx
  src/components/templates/PageTemplate/PageTemplate.styles.ts
  src/components/templates/PageTemplate/PageTemplate.tsx
  src/stories/components/atoms/Icon.stories.tsx
Labels: 분류 : 기능 추가 / 개선, 우선순위 : 중간

#183 [ 혜수 ] resize store 추가
  src/components/templates/PageTemplate/PageTemplate.tsx
  src/stores/resize.store.ts
Labels: 분류 : 기능 추가 / 개선, 우선순위 : 중간

#185 [ 진욱 ] 에디터 전체화면 버튼 없애기
  src/components/molecules/CommentForm.tsx
  src/components/organisms/ArticleWrite/ArticleEdit.tsx
  src/components/organisms/ArticleWrite/ArticleWrite.tsx
  src/styles/globalStyles.ts
Labels: 분류 : 버그, 우선순위 : 중간

#191 [ 진욱 ] 하트 아이콘 색 입히기
  src/components/organisms/ArticleHeader/ArticleHeader.tsx
  src/components/organisms/Card/CardFooter.tsx
  src/constants/theme.ts
Labels: 분류 : 기능 추가 / 개선, 우선순위 : 낮음

#193 [ 진욱 ] 자신의 게시글에 댓글 작성 시 알림 생성 방지
  src/components/molecules/CommentForm.tsx
Labels: 분류 : 버그, 우선순위 : 긴급

#201 [ 진욱 ] 드롭다운 컴포넌트 리액트 포탈로 변경
  src/components/atoms/Dropdown.tsx
  src/components/organisms/NotiDropdown/NotiDropdown.styles.ts
  src/components/organisms/NotiDropdown/NotiDropdown.tsx
  src/components/organisms/Sidebar/SidebarMain.tsx
Labels: 분류 : 버그, 우선순위 : 긴급

#203 [ 진욱 ] 카드, 검색결과, 게시글에 어느 채널인지 표시해주는 기능 추가
  src/apis/search/searchArticles.ts
  src/components/molecules/UserInfo.tsx
  src/components/organisms/ArticleHeader/ArticleHeader.tsx
  src/components/organisms/Card/Card.styles.ts
  src/components/organisms/Card/Card.tsx
  src/components/organisms/CardList/CardList.tsx
  src/components/organisms/SearchModal/SearchItem.tsx
  src/hooks/useChannelName.ts
  src/pages/ChannelPage/ChannelPageSkeleton.tsx
  src/pages/SearchPage/SearchPage.tsx
  src/pages/UserPage/ArticleList.tsx
  src/types/apis/etc/SearchAll.ts
Labels: 분류 : 기능 추가 / 개선, 우선순위 : 중간

#207 [ 진욱 ] 검색, 유저페이지 로딩처리
  src/components/molecules/FallbackPage.tsx
  src/components/molecules/Spinning.tsx
  src/components/organisms/Article/ArticleSkeleton.tsx
  src/components/organisms/Article/index.ts
  src/router/index.tsx
Labels: 분류 : 기능 추가 / 개선, 우선순위 : 중간

#211 [ 진욱 ] 마크다운을 텍스트로 변환하는 라이브러리 추가하기
  package-lock.json
  package.json
  src/components/organisms/ArticleWrite/ArticleWriteEditor.tsx
  src/components/organisms/Card/CardFooter.tsx
  src/utils/markdownToPlainText.ts
Labels: 분류 : 기능 추가 / 개선, 우선순위 : 긴급

#209 [ 진욱 ] 유저페이지 채널탭에 탐색 버튼 추가
  src/pages/UserPage/ChannelTab.styles.ts
  src/pages/UserPage/ChannelTab.tsx
Labels: 분류 : 기능 추가 / 개선, 우선순위 : 중간

#213 [ 진욱 ] 편집기 작성버튼 위치 수정, 좋아요 알림 안가던 것 수정
  src/components/molecules/EmptyAlert/EmptyAlert.styles.ts
  src/components/organisms/Article/Article.styles.ts
  src/components/organisms/ArticleHeader/ArticleHeader.tsx
  src/components/organisms/ArticleWrite/ArticleEdit.tsx
  src/components/organisms/ArticleWrite/ArticleWrite.styles.ts
  src/components/organisms/ArticleWrite/ArticleWrite.tsx
  src/components/organisms/NotiDropdown/NotiDropdown.tsx
  src/types/models/Notification.ts
Labels: 분류 : 기능 추가 / 개선, 우선순위 : 중간

#195 [ 동현 ] 유저 정보 변경 기능 개선
  src/hooks/api/useUserProfileUploadMutation.ts
  src/hooks/api/useUserUpdateMutation.ts
  src/pages/UserPage/UserPage.tsx
Labels: 분류 : 기능 추가 / 개선, 우선순위 : 중간

#198 [ 동현 ] 회원가입, 로그인, 패스워드 변경 성공 시 toast UI 띄우기, 닉네임 정규식 패턴 수정
  src/constants/regex.ts
  src/pages/LoginPage.tsx
  src/pages/PasswordPage.tsx
  src/pages/SignUpPage.tsx
Labels: 분류 : 기능 추가 / 개선, 우선순위 : 중간

#215 [ 혜수 ] 사이드바 반응형 수정
  .prettierrc
  src/components/organisms/ArticleWrite/ArticleWrite.styles.ts
  src/components/organisms/Sidebar/Sidebar.styles.ts
  src/components/organisms/Sidebar/Sidebar.tsx
  src/components/organisms/Sidebar/SidebarAppearButton.tsx
  src/components/organisms/Sidebar/SidebarHeader.tsx
  src/components/organisms/Sidebar/SidebarMain.tsx
  src/components/templates/PageTemplate/PageTemplate.styles.ts
  src/components/templates/PageTemplate/PageTemplate.tsx
  src/contexts/sidebar.context.tsx
  src/hooks/contexts/useSidebarContext.ts
  tsconfig.json
  vite.config.ts
Labels: 분류 : 기능 추가 / 개선, 우선순위 : 긴급

#220 [ 혜수 ] 로그아웃시 모달로 확인하기
  src/components/molecules/ConfirmModal.tsx
  src/components/organisms/Sidebar/SidebarFooter.tsx
Labels: 분류 : 기능 추가 / 개선, 우선순위 : 낮음

#218 [ 진욱 ] 유저페이지 반응형 수정
  src/pages/UserPage/ChannelTab.tsx
  src/pages/UserPage/UserInfo.tsx
  src/pages/UserPage/UserPage.tsx
Labels: 분류 : 버그, 우선순위 : 긴급

#221 [ 진욱 ] 게시글 페이지에서 글 작성 버튼 위치 조정
  src/components/organisms/FloatingButtons/FloatingButtons.tsx
Labels: 분류 : 버그, 우선순위 : 긴급

#226 [ 진욱 ] 안읽은 알림 있을 때 아이콘에 표시기능
  src/components/organisms/NotiDropdown/NotiDropdown.styles.ts
  src/components/organisms/NotiDropdown/NotiDropdown.tsx
  src/components/organisms/Sidebar/NotificationItem.tsx
  src/components/organisms/Sidebar/SidebarMain.tsx
  src/hooks/api/useNotificationsQuery.ts
Labels: 분류 : 기능 추가 / 개선, 우선순위 : 중간

#227 [ 동현 ] 디펜던시 어레이 안채워진 것 수정(로그인, 회원가입, 비밀번호 변경페이지) ,로그인페이지 비동기부분 훅 분리
  src/hooks/api/useLoginMutation.ts
  src/hooks/api/useSignUpMutation.ts
  src/hooks/api/useUserPasswordUpdateMutation.ts
  src/main.tsx
  src/pages/LoginPage.tsx
  src/pages/PasswordPage.tsx
  src/pages/SignUpPage.tsx
Labels: 분류 : 기능 추가 / 개선, 우선순위 : 중간

#228 [ 동현 ] 글 작성시 CORS 에러로 인한 썸네일 업로드 방식 변경
  src/components/organisms/ArticleWrite/ArticleWriteButtons.tsx
  src/components/organisms/ArticleWrite/ThumnailChooseModal.tsx
  src/utils/extractImageUrls.ts
  src/utils/urlToImageFile.ts
Labels: 분류 : 기능 추가 / 개선, 우선순위 : 긴급

#229 [ 혜수 ] 사이드바 스크롤 이벤트 버블링 현상 막기 완료
  src/components/organisms/Sidebar/SidebarChannels.tsx
Labels: 분류 : 버그, 우선순위 : 중간

#231 [ 진욱 ] 파비콘, 타이틀 변경하기
  index.html
  package-lock.json
  package.json
  public/scrawl.svg
  src/components/organisms/Article/Article.tsx
  src/components/organisms/ArticleWrite/ArticleEdit.tsx
  src/components/organisms/ArticleWrite/ArticleWrite.tsx
  src/main.tsx
  src/pages/ChannelPage/ChannelPage.tsx
  src/pages/ErrorPage.tsx
  src/pages/HomePage/HomePage.tsx
  src/pages/LoginPage.tsx
  src/pages/PasswordPage.tsx
  src/pages/SearchPage/SearchPage.tsx
  src/pages/SignUpPage.tsx
  src/pages/UserPage/UserPage.tsx
Labels: 분류 : 기능 추가 / 개선, 우선순위 : 중간

#233 [ 혜수 ] 좁은 너비에서 사이드바 밖 부분 클릭시 사이드바 닫히는 기능 추가
  src/components/organisms/Sidebar/Sidebar.styles.ts
  src/components/templates/PageTemplate/PageTemplate.tsx
Labels: 분류 : 기능 추가 / 개선, 우선순위 : 낮음

#235 [ 배포 ] 스크롤 버그 수정 후 재배포
  src/components/organisms/Article/Article.tsx
  src/styles/globalStyles.ts
Labels: 분류 : 배포

#236 [ 배포 ] 로고 svg 수정, 글 작성, 수정 페이지 디자인 수정
  index.html
  public/scrawl.svg
  src/assets/svg/logo.svg
  src/assets/svg/logoAlert.svg
  src/assets/svg/logoSuccess.svg
  src/assets/svg/noImage.svg
  src/components/organisms/ArticleWrite/ArticleEdit.tsx
  src/components/organisms/ArticleWrite/ArticleWrite.tsx
Labels: 분류 : 배포

#237 [ 배포 ] 썸네일 모달 이미지 없음 문제 해결
  src/components/organisms/ArticleWrite/ThumnailChooseModal.tsx
Labels: 분류 : 배포

#238 [ 진욱 ] 스크롤 맨 위로 올리는 훅 작성 및 적용
  src/components/molecules/FallbackPage.tsx
  src/components/organisms/Article/Article.tsx
  src/hooks/api/useArticlesByChannelIdQuery.ts
  src/hooks/useScrollToTop.ts
  src/pages/ChannelPage/ChannelPage.tsx
  src/pages/ChannelPage/ChannelPageSkeleton.tsx
  src/pages/HomePage/HomePage.tsx
  src/pages/HomePage/HomePageSkeleton.tsx
  src/pages/SearchPage/SearchPage.tsx
  src/pages/UserPage/UserPage.tsx
Labels: 분류 : 기능 추가 / 개선

#240 Readme update
  README.md
Labels: 분류 : 배포
